import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { geologica, geologicaSharp, geologicaVariable, poppins } from "./ui/fonts";

export const metadata: Metadata = {
  title: "SVG Path Generator",
  description: "SVG Path Generator app generated by 'create-next-app' using 'Vercel-postgre', 'NextJS' and 'Drizzle', and built by NJTD",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${geologica.className} ${geologicaSharp.className} ${geologicaVariable.className}`}>{children}</body>
    </html>
  );
}
